config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'accounts#index'
  resources :accounts, only: [:index, :show, :new, :create]
  resources :accounts, only: [] do
    resources :users, only: [:index, :new, :create], module: :accounts
    resources :subscriptions, only: [:index, :new, :create], module: :accounts
    resources :license_assignments, only: [:index, :create], module: :accounts do
      collection do
        post :unassign
      end
    end
  end
  resources :products, only: [:index, :show, :new, :create]
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
  belongs_to :account

  has_many :license_assignments, dependent: :destroy

  scope :ordered_by_name, -> { order(:name) }

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/accounts/users_controller.rb
# frozen_string_literal: true

module Accounts
  class UsersController < ApplicationController
    before_action :set_account

    def index
      @users = @account.users.ordered_by_name
    end

    def new
      @user = @account.users.new
    end

    def create
      @user = @account.users.create!(user_params)
      redirect_to account_users_path(@account), notice: "User was successfully created."
    end

    private

    def set_account
      @account = Account.find(params[:account_id])
    end

    def user_params
      params.require(:user).require(:name)
      params.require(:user).require(:email)
      params.require(:user).permit(:name, :email)
    end
  end
end

app/views/users/_form.html.erb
<%= form_with model: [@account, user] do |form| %>
  <% if user.errors.any? %>
    <div>
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name, autofocus: true %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.submit "Create User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users for <%= @account.name %></h1>

<p>
  <%= link_to "New User", new_account_user_path(@account) %>
  |
  <%= link_to "Back to Account", account_path(@account) %>
</p>

<% if @users.any? %>
  <ul>
    <% @users.each do |user| %>
      <li><%= user.name %> (<%= user.email %>)</li>
    <% end %>
  </ul>
<% else %>
  <p>No users yet.</p>
<% end %>

app/views/users/new.html.erb
<h1>New User for <%= @account.name %></h1>

<%= render "form", user: @user %>

<p>
  <%= link_to "Back", account_users_path(@account) %>
</p>